# Pandas Dataframes

© Explore Data Science Academy

## Instructions to Students
- **Do not add or remove cells in this notebook. Do not edit or remove the `### START FUNCTION` or `### END FUNCTION` comments. Do not add any code outside of the functions you are required to edit. Doing any of this will lead to a mark of 0%!**
- Answer the questions according to the specifications provided.
- Use the given cell in each question to to see if your function matches the expected outputs.
- Do not hard-code answers to the questions.
- The use of stackoverflow, google, and other online tools are permitted. However, copying fellow student's code is not permissible and is considered a breach of the Honour code below. Doing this will result in a mark of 0%.
- Good luck, and may the force be with you!

## Honour Code

I **Tracy, Mutugi**, confirm - by submitting this document - that the solutions in this notebook are a result of my own work and that I abide by the   <a href="https://drive.google.com/open?id=1FXCIf425JLRx3JQi-ltSWppj8BCF3Np1" target="_blank">EDSA Student Manifesto</a>.

Non-compliance with the honour code constitutes a material breach of contract.

### Import the required libraries

In [0]:
import numpy as np
import pandas as pd

### Data

You will need these dataframes in order to answer the following questions.

In [0]:
country_map_df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/AnalyseProject/country_code_map.csv', index_col='Country Code')
population_df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/AnalyseProject/world_population.csv', index_col='Country Code')
meta_df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/AnalyseProject/metadata.csv', index_col='Country Code')

_**Dataframe specifications:**_

The dataframes provide information about the population of the world for various years. Some things to note:
* All dataframes have a `Country Code` as an index, which is a three letter code referring to a country.
* The `country_map_df` data maps the `Country Code` to a `Country Name`.
* The `population_df` data contains information on the population for a given country between the years of 1960 and 2017.
* The `meta_df` data contains meta information about each country, including it's geographical region, it's income group, and a comment on the country as a whole.

In [4]:
country_map_df.head()

Country Name
Country Code             
ABW                 Aruba
AFG           Afghanistan
AGO                Angola
ALB               Albania
AND               Andorra

In [5]:
population_df.head()

1960       1961  ...        2016        2017
Country Code                        ...                        
ABW             54211.0    55438.0  ...    104822.0    105264.0
AFG           8996351.0  9166764.0  ...  34656032.0  35530081.0
AGO           5643182.0  5753024.0  ...  28813463.0  29784193.0
ALB           1608800.0  1659800.0  ...   2876101.0   2873457.0
AND             13411.0    14375.0  ...     77281.0     76965.0

[5 rows x 58 columns]

In [6]:
meta_df.head()

Region  ...                                      Special Notes
Country Code                             ...                                                   
ABW           Latin America & Caribbean  ...  Mining is included in agriculture\r\r\r\nElect...
AFG                          South Asia  ...  Fiscal year end: March 20; reporting period fo...
AGO                  Sub-Saharan Africa  ...                                                NaN
ALB               Europe & Central Asia  ...                                                NaN
AND               Europe & Central Asia  ...  WB-3 code changed from ADO to AND to align wit...

[5 rows x 3 columns]

Using this information, answer the questions below:

### Question 1

Write a function that returns the summed population total in a given geographic region for a given year.

_**Function Specifications:**_
* Should take as input a year as an `int` and region as a `str`.
* Should return an `int` corresponding to the population.

In [0]:
### START FUNCTION
def total_pop_in_region(year,region):
  popdata1_df = population_df.copy(deep=True)
  metadata1_df = meta_df.copy(deep=True)

  popdata1_df['Region'] = metadata1_df['Region']
      
  output1 = popdata1_df[popdata1_df['Region'].str.contains(region)].sum()
  return output1[str(year)]

### END FUNCTION

In [8]:
total_pop_in_region(1960,'East Asia & Pacific')

1029332591.0

_**Expected Outputs:**_
```python
total_pop_in_region(1960,'East Asia & Pacific') == 1029332591.0
total_pop_in_region(1970,'South Asia') == 712740919.0
```

### Question 2

Write a function that returns the global yearly population `Growth`, grouped by the `Income Group` and `Year`.

_**Function Specifications**_
* Should not take any inputs.
* The years are currently presented as the heading of each row in the population table. The table will have to be melted to produce the appropriate format. You can use `df.melt` to do this, where the variable name should be `Year` and the value name should be `Growth`.
* Should group by the `Year` and `Income Group`.
* Should only have one column named `Growth`.
* The `Income Group` and the `Year` should be indices.
* The `Growth` is calculated by taking the yearly difference and dividing it by the total population for each year, multiplied by 100.
* Should return a `DataFrame`.

In [0]:
### START FUNCTION
def population_difference_by_income():
  popdata2_df = population_df.copy(deep=True)
  metadata2_df = meta_df.copy(deep=True)
  popdata2_df['Income Group'] = metadata2_df['Income Group']

  new_df = popdata2_df.reset_index()
  #new_df.head()

  new_melt = pd.melt(new_df, id_vars = ['Country Code', 'Income Group'], var_name = 'Year', value_name = 'POP-Growth')
  #new_melt

  ##GROUPBY METHOD
  new_group = new_melt.groupby(['Income Group','Year'])['POP-Growth'].sum()
  #new_group
  new_group2 = pd.DataFrame(new_group)
  #new_group2

  new_group2['pop-growth_shift'] = new_group2['POP-Growth'].shift(1)
  new_group2['Growth'] = (new_group2['POP-Growth']-new_group2['pop-growth_shift'])/new_group2['POP-Growth']*100
  #new_group2

  new_group3 = new_group2.drop(columns=['POP-Growth', 'pop-growth_shift'])
  
  return new_group3

### END FUNCTION

In [10]:
population_difference_by_income().head()

Growth
Income Group Year          
High income  1960       NaN
             1961  1.450978
             1962  1.261630
             1963  1.235893
             1964  1.207633

_**Expected Output:**_
```python
population_difference_by_income().head()
```
> <table class="dataframe" border="1">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th>Growth</th>
    </tr>
    <tr>
      <th>Income Group</th>
      <th>Year</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="5" valign="top">High income</th>
      <th>1960</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1961</th>
      <td>1.450978</td>
    </tr>
    <tr>
      <th>1962</th>
      <td>1.261630</td>
    </tr>
    <tr>
      <th>1963</th>
      <td>1.235893</td>
    </tr>
    <tr>
      <th>1964</th>
      <td>1.207633</td>
    </tr>
  </tbody>
</table>

### Question 3

Using the function you just created, write a function that returns the average population _growth_ over all years for a given income group. 

_**Function Specifications:**_
* Should take as input a `str` as the income group.
* Should raise a `ValueError` if the input is not a valid income group.
* Should return a `float`, rounded to 2 decimal places.

In [0]:
### START FUNCTION
def ave_growth_by_income(income_group):
  ##STEP 1 previous function
  popdata2_df = population_df.copy(deep=True)
  metadata2_df = meta_df.copy(deep=True)
  popdata2_df['Income Group'] = metadata2_df['Income Group']

  new_df = popdata2_df.reset_index()
  #new_df.head()

  new_melt = pd.melt(new_df, id_vars = ['Country Code', 'Income Group'], var_name = 'Year', value_name = 'POP-Growth')
  #new_melt

  ##GROUPBY METHOD
  new_group = new_melt.groupby(['Income Group','Year'])['POP-Growth'].sum()
  #new_group
  new_group2 = pd.DataFrame(new_group)
  #new_group2

  new_group2['pop-growth_shift'] = new_group2['POP-Growth'].shift(1)
  new_group2['Growth'] = (new_group2['POP-Growth']-new_group2['pop-growth_shift'])/new_group2['POP-Growth']*100
  #new_group2

  new_group3 = new_group2.drop(columns=['POP-Growth', 'pop-growth_shift'])
  new_group3.loc['Lower middle income','1960']['Growth'] = np.nan
  new_group3.loc['Low income','1960']['Growth'] = np.nan
  new_group3.loc['Upper middle income','1960']['Growth'] = np.nan

  mean_growth = new_group3.groupby('Income Group')['Growth'].mean()
  mean_growth_df = pd.DataFrame(mean_growth)
  #mean_growth_df

  ##STEP 2
  if str(income_group) not in mean_growth.index:
      raise ValueError(income_group + '-' + 'is an invalid income group')

  output1 = mean_growth_df.loc[str(income_group)]['Growth']
  output3 = round(output1, 2)
  return output3

### END FUNCTION

In [14]:
ave_growth_by_income('Low income')

2.55

_**Expected Outputs:**_
```python
ave_growth_by_income('High income') == 0.81
ave_growth_by_income('Low income') == 2.55
```